### ISSUE TITLE
Question about the mutual information in the agmax loss

### ISSUE THREAD

**Issue by YananGu** [roatienza/agmax#1]
The agmax loss is computed by "agreement_loss, dl = agmax_loss(y, target, self.args.dl_weight)" , 
 I do not know what does the argeement_loss and dl mean,  and do not know the relationship between these two loss and the calculation of mutual information.  Could you give me some help?

**Comment by roatienza** [comment]
agreement_loss is the approximate mi loss. dl is a distance loss that forces the joint and marginal distributions to be the same so that the agreement_loss (which is entropy loss) is a good approximation of mi loss.
<img width="436" alt="mi_loss" src="https://user-images.githubusercontent.com/8848769/140302101-c416fa1e-28d3-4e46-bdf7-55b395e41f3d.png">

**Comment by YananGu** [comment]
Thank you very much for your reply. Does it means that  dl is not a necessary component for calculating MI?  And could you tell me how this formula is derived, or  in which paper this formula was proposed? Thanks again.

**Comment by roatienza** [comment]
minimizing dl is important so that the entropy loss is a good approximation of mi loss. the formula can be derived from the definition of mi and one of the expressions to calculate mi.

**Comment by YananGu** [comment]
Get it, thank you very much

**Comment by YananGu** [comment]
I'm sorry to bother you again. I tried to deduce this formula, but failed. Can you provide a specific idea or process for deriving this formula..
